USE [hd]
GO

/****** Object:  Table [dbo].[Description]    Script Date: 09.05.2018 20:58:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Description](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[Text] [varchar](100) NULL,
 CONSTRAINT [PK_Description] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


